// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-FzB5qhRzfBCVPlBEcX_As1ercpCn78',
    appId: '1:870682354873:web:e4bf924f1cdcd89390a768',
    messagingSenderId: '870682354873',
    projectId: 'guided-traveler',
    authDomain: 'guided-traveler.firebaseapp.com',
    storageBucket: 'guided-traveler.appspot.com',
    measurementId: 'G-MZVX6JCHHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgRH8feLK6Z7snLoZmZSAELeDkfXrCXSc',
    appId: '1:870682354873:android:5d4495b516bad83f90a768',
    messagingSenderId: '870682354873',
    projectId: 'guided-traveler',
    storageBucket: 'guided-traveler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlHGTQ4F6TXasGiVEOpw7CnD-W-Yteovc',
    appId: '1:870682354873:ios:d5c2598d88eab75f90a768',
    messagingSenderId: '870682354873',
    projectId: 'guided-traveler',
    storageBucket: 'guided-traveler.appspot.com',
    iosClientId: '870682354873-2e8ot9b54hur1seurk5obn1mpob4lfi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.guidedTraveler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlHGTQ4F6TXasGiVEOpw7CnD-W-Yteovc',
    appId: '1:870682354873:ios:d5c2598d88eab75f90a768',
    messagingSenderId: '870682354873',
    projectId: 'guided-traveler',
    storageBucket: 'guided-traveler.appspot.com',
    iosClientId: '870682354873-2e8ot9b54hur1seurk5obn1mpob4lfi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.guidedTraveler',
  );
}
